import userPhoto from "./img/user.png";
import photo from "./img/apple.jpg";
export const data = [
  {
    name: "Feb",
    "Active User": 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Mar",
    "Active User": 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "Apr",
    "Active User": 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "May",
    "Active User": 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "Jun",
    "Active User": 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "July",
    "Active User": 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Aug",
    "Active User": 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Seb",
    "Active User": 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Oct",
    "Active User": 3490,
    pv: 4300,
    amt: 2100,
  },
];
export const productData = [
  {
    name: "Feb",
    Sales: 4000,
  },
  {
    name: "Mar",
    Sales: 3000,
  },
  {
    name: "Apr",
    Sales: 2000,
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 2,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 3,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 4,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 5,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 6,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 7,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 8,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 9,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 10,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
  {
    id: 11,
    name: "Apple Watch",
    img: `${photo}`,
    stock: 87,
    status: "Active",
    price: "$340.11",
  },
];

export const userRows = [
  {
    id: 1,
    userName: "Snow",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 2,
    userName: "Oto",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 3,
    userName: "Todo",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 4,
    userName: "Demo",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 5,
    userName: "Wido",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 6,
    userName: "Moto",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 7,
    userName: "Ice",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 8,
    userName: "Wise",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 9,
    userName: "Nice",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 10,
    userName: "Dano",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
  {
    id: 11,
    userName: "Nano",
    avatar: `${userPhoto}`,
    email: "jon@gmail.com",
    status: "Active",
    transaction: "$340.11",
  },
];
